export const PortfolioData = [
  {
    id: 0,
    title: "Software Engineering Intern at Avodigy",
    type: "Career",
    brief: "Android and Firebase development for the Eventpedia mobile app.",
    preview: "AvodigyPreview.png",
    imageList: ["AvodigyPreview.png"],
    description: [
      "Avodigy develops software for events, associations, and online communities. Its products include Eventpedia, which provides native and web apps with event schedules, attendee and exhibitor profiles, notifications, document sharing, personalized calendars, interactive maps, and analytics.",
      "As a software engineering intern, I worked on Eventpedia's Android app. I developed features that let attendees use social feeds, publish posts, manage connections, and receive notifications.",
      "I built the Android interfaces for social feeds and posts, connected them to Firebase Firestore, and designed Firestore data models for feeds, friend relationships, and notifications. I considered query efficiency and database cost when designing each model.",
    ],
    highlights: [
      "Built Android interfaces for Eventpedia social feeds and posts.",
      "Connected app features to Firebase Firestore.",
      "Designed data models for feeds, friend relationships, and notifications with attention to query cost.",
    ],
    stack: ["Android", "Firebase Firestore", "Mobile UI", "Data Modeling"],
    date: 202005,
    location: "Remote/McLean, VA",
    links: [{ label: "Visit Avodigy", url: "https://www.avodigy.com/" }],
  },
  {
    id: 1,
    title: "Scotty Security",
    type: "Project",
    brief: "An all-in-one app for CMU safety, health, and alerting resources.",
    preview: "scottypreview.png",
    imageList: ["scottypreview.png"],
    description: [
      "We created Scotty Security because Carnegie Mellon safety, health, and alerting resources were spread across separate services. Our goal was to provide one app where students could quickly find help and use practical safety tools. We named it Scotty Security after Carnegie Mellon's Scotty dog mascot.",
      "Our team built a Cordova and Node.js prototype with location tracking, CMU police access, campus maps, news notifications, an emergency whistle, audio recording, and contacts. I led much of the front-end implementation and helped teammates ramp up on HTML, CSS, and JavaScript during the hackathon.",
    ],
    highlights: [
      "Led much of the front-end implementation during TartanHacks.",
      "Designed the app as a central location for CMU safety, health, and alerting resources.",
      "Combined location tracking, campus maps, police access, notifications, recording, and contacts.",
      "Helped teammates ramp up on HTML, CSS, and JavaScript during the hackathon.",
    ],
    stack: ["Cordova", "Node.js", "HTML", "CSS", "JavaScript"],
    date: 202002,
    location: "Carnegie Mellon University",
  },
  {
    id: 2,
    title: "Ajenda",
    type: "Project",
    brief: "An Android app for comparing schedules and finding shared free time.",
    preview: "AjendaPreview.png",
    imageList: ["AjendaPreview.png"],
    description: [
      "I started Ajenda because scheduling time with friends was difficult. Google Calendar and similar tools supported formal event planning, but they did not provide the polling and schedule compatibility features that I wanted for casual group plans. My goal was to build an app that could compare schedules, identify shared free time, and schedule an event automatically.",
      "Ajenda was my first substantial personal software project. I had completed AP Computer Science in high school, but I had limited experience turning an idea into a working product. I chose Android because I wanted to build a mobile app and because Android Studio gave me an accessible way to create and test a complete user interface.",
      "I built calendar functionality, persistent event storage, and a custom calendar interface. I also integrated OpenWeatherMap data and Google Maps travel times to provide additional scheduling information.",
      "The project taught me the basics of building a product from an initial idea through implementation. I learned Android application structure, activity and fragment lifecycles, XML layouts, event handling, persistent storage, API integration, asynchronous operations, and debugging. I later used these skills during my internship at Avodigy.",
    ],
    highlights: [
      "Built custom Android calendar UI and persistent event storage.",
      "Explored constraint-based placement of recurring goals and events.",
      "Integrated weather data from OpenWeatherMap and travel times from Google Maps.",
      "Learned Android fundamentals and the process of building a product from an initial idea.",
    ],
    stack: [
      "Android Studio",
      "OpenWeatherMap",
      "Google Maps",
      "Calendar UI",
      "Persistent Storage",
    ],
    date: 201905,
    location: "Boston, MA",
  },
  {
    id: 3,
    title: "Network Automation Intern at NetBrain Technologies",
    type: "Career",
    brief: "Network automation, topology mapping, and ServiceNow integration.",
    preview: "NetBrainPreview.png",
    imageList: ["NetBrainPreview.png"],
    description: [
      "NetBrain provides a network operations platform that discovers and maps hybrid networks, automates troubleshooting and assessments, supports safer network changes, and integrates with systems such as ServiceNow and Jira. The platform helps network teams replace manual operational work with documented and repeatable automation.",
      "As a network automation intern, I wrote Python automation scripts using tools such as Netmiko, NAPALM, and Paramiko to connect to routers and switches. I created Ansible playbooks and NetBrain low-code intents for repetitive configuration changes, and I tested automation code in virtual network labs before deployment.",
      "I worked on integrations between network systems and external tools, including a JavaScript proof of concept for ServiceNow and validation of NetBrain REST API use cases with Python HTTP scripts. I also helped discover and document hybrid network topologies using automated mapping tools.",
      "To process device output, I wrote regular expressions and TextFSM templates that extracted structured data from raw command-line results. I used Git and GitHub to maintain the team's automation code and documentation, and I wrote automation for extracting and updating network data in MongoDB.",
    ],
    highlights: [
      "Wrote Python automation scripts for routers and switches using Netmiko, NAPALM, and Paramiko.",
      "Created Ansible playbooks and NetBrain low-code intents for repetitive network changes.",
      "Built a JavaScript proof of concept for ServiceNow integration and validated NetBrain REST APIs.",
      "Used Regex and TextFSM to convert raw command-line output into structured data.",
      "Helped discover, document, and map hybrid network topologies.",
    ],
    stack: [
      "Python",
      "Netmiko",
      "NAPALM",
      "Paramiko",
      "Ansible",
      "REST APIs",
      "ServiceNow",
      "Regex",
      "TextFSM",
      "Virtual Network Labs",
      "MongoDB",
      "Git",
    ],
    date: 201905,
    location: "Burlington, MA",
    links: [{ label: "Visit NetBrain", url: "https://www.netbrain.com/" }],
  },
  {
    id: 4,
    title: "Research Intern in Simon Robson's Lab",
    type: "Research",
    brief:
      "Harvard Medical School research on CD39L3 glycoforms and fatty liver disease.",
    preview: "cd39l3preview.png",
    imageList: ["cd39l3preview.png"],
    description: [
      "As a Harvard Medical School intern in Professor Simon Robson's lab at Beth Israel Deaconess Medical Center, I contributed to research on CD39L3 glycoforms and fatty liver disease. I worked closely with Gordon Jiang, Bynvant Sandhu, Maria C. Perez Matos, and Stephanie Tran.",
      "My laboratory responsibilities included collecting mouse tail tissue samples, helping administer experimental diets, assisting with direct blood collection, pipetting, western blotting, gel electrophoresis, and centrifugation.",
      "I used HALO digital pathology software for whole-slide image analysis. The software analyzed digitized tissue slides and quantified selected cell types and biological markers.",
      "I also studied glycoforms of the pancreatic protein CD39L3. The project examined how carbohydrate structures attached to CD39L3 affect enzymatic activity within purinergic signaling.",
      "I created and analyzed multiple glycoforms and modeled the structural implications of those modifications. The results showed that different N-glycan attachments could substantially alter NTPDase activity and affect the enzyme's catalytic behavior.",
      'The CD39L3 research was published as a first-author paper in "Purinergic Signaling," and I was named a Regeneron Science Talent Search National Semifinalist. I was also a co-author on a JHEP Reports paper studying cell-specific PNPLA3 transcription in non-alcoholic fatty liver disease.',
    ],
    highlights: [
      "Worked as a Harvard Medical School intern in Simon Robson's lab.",
      "Collected mouse tail tissue samples, helped administer testing diets, and assisted with direct blood collection.",
      "Performed pipetting, western blotting, gel electrophoresis, and centrifugation.",
      "Used HALO digital pathology software for whole-slide image analysis.",
      "Created and analyzed multiple CD39L3 glycoforms.",
      "Modeled how glycan modifications affect enzymatic structure and activity.",
      'Published a first-author paper in "Purinergic Signaling."',
      "Co-authored research on cell-specific PNPLA3 transcription and fatty liver disease.",
      "Named a Regeneron Science Talent Search National Semifinalist.",
    ],
    stack: [
      "Protein Glycosylation",
      "Structural Modeling",
      "HALO Digital Pathology",
      "Whole-slide Image Analysis",
      "Western Blotting",
      "Gel Electrophoresis",
      "Centrifugation",
      "Pipetting",
    ],
    date: 201702,
    location: "Harvard Medical School",
    links: [
      {
        label: "Read published paper",
        url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5714850/",
      },
      {
        label: "Read PNPLA3 and NAFLD study",
        url: "https://www.jhep-reports.eu/article/S2589-5559(19)30055-2/pdf",
      },
    ],
  },
  {
    id: 8,
    title: "Software Engineer at Google Payments",
    type: "Career",
    brief:
      "Full-stack engineering for GPay US and the Pix integration in Google Wallet.",
    preview: "",
    imageList: [],
    description: [
      "I joined Google Payments on the GPay US team, which developed features for the United States version of the GPay app. GPay originated in India, where it became widely used for peer-to-peer and peer-to-merchant payments. Google later adapted the product for the United States through several versions that combined payments, Google Wallet features, and financial insights.",
      "When I joined, the team was developing GPay3, a peer-to-peer payments and financial insights app built with Flutter and Dart. It was the largest Flutter-based product at Google at the time. I joined with Android development experience but no prior Dart experience, and I learned the language while working as a full-stack engineer across the app and its supporting services.",
      "One of the features I built was recurring transaction management. It allowed users to manage subscriptions and recurring charges, including services such as Netflix and DoorDash, by choosing which transactions appeared in the app.",
      "After the post-COVID layoffs, the GPay US team was deprioritized and lost several members. Leadership later decided to turn down the app, and I helped deprecate its features and supporting systems.",
      "I then moved to the GPay Brazil team, where I currently help integrate Pix, Brazil's instant payment system, into Google Wallet. I work across client and server code, including an internal orchestration system that displays server-driven interfaces using data retrieved from other services.",
      "I recently helped launch a Pix balance feature that displays a user's account balance in Google Wallet. The feature launched in an April 2026 pilot with the Central Bank of Brazil. The product has since passed one million monthly transacting users and several million linked accounts.",
    ],
    highlights: [
      "Built recurring transaction management for the Flutter and Dart-based GPay US app.",
      "Helped deprecate GPay US after the product was turned down.",
      "Developed client and server features for integrating Pix into Google Wallet.",
      "Helped launch Pix account balance support in an April 2026 Central Bank of Brazil pilot.",
      "Supported a product that has passed one million monthly transacting users and several million linked accounts.",
    ],
    stack: [
      "Flutter",
      "Dart",
      "Java",
      "TypeScript",
      "Server-driven UI",
      "Google Wallet",
      "GPay",
      "Pix",
    ],
    date: 202206,
    location: "Mountain View, CA",
  },
  {
    id: 9,
    title: "Software Engineering Intern at Google Payments Autofill",
    type: "Career",
    brief:
      "Built backend risk-signal infrastructure supporting secure virtual card enrollment and retrieval.",
    preview: "",
    imageList: [],
    description: [
      "The Payments Autofill team supports online checkout in Google Chrome and on Android by automatically filling saved addresses and payment information.",
      "One team project was Virtual Card Numbers. VCN replaces a user's credit card number with a secure token, which prevents merchants from receiving the underlying card number and allows card issuers to use risk signals during enrollment and retrieval.",
      "During my internship, I implemented an Ares Oar feature provider service that shared anonymized risk signals with external card issuers. Ares is an anti-abuse platform, and Oar is its rule system. The service provided assessments such as account age, device bonding age, and security update frequency.",
      "I defined Protocol Buffer messages and bucketing enums, integrated the service with sources including the UserDeviceRisk API, and established service dependencies and client access controls. I also replaced an incompatible client-side experimentation framework with Abseil flags for controlled backend rollout in testing and production.",
    ],
    highlights: [
      "Implemented an Ares Oar feature provider service that shared anonymized risk signals with external card issuers during virtual card enrollment and retrieval.",
      "Defined Protocol Buffer messages and bucketing enums to isolate account, device-bonding, and security-update risk signals.",
      "Integrated the service with the UserDeviceRisk API and established service dependencies and client access controls for issuer partners.",
      "Replaced a client-side experimentation framework with Abseil flag controls for safe backend rollout across testing and production environments.",
    ],
    stack: [
      "Protocol Buffers",
      "Ares / Oar",
      "Abseil Flags",
      "Backend APIs",
      "Access Controls",
      "Payments Security",
    ],
    date: 202108,
    location: "Mountain View, CA",
  },
  {
    id: 5,
    title: "Wanderform.com",
    type: "Project",
    brief:
      "AI travel planner web app for generating and refining structured itineraries.",
    preview: "WanderformTrips.png",
    imageList: [
      "WanderformTrips.png",
      "WanderformCreatePlan.png",
      "WanderformItinerary.png",
    ],
    description: [
      "I built Wanderform as an AI travel planner that turns trip constraints into structured, editable itineraries. Users can save trips, review generated plans, and revise individual events.",
      "The app uses React, Vite, Tailwind CSS, and shadcn/ui on the frontend, with Express, Firebase Auth, Firestore, and LLM APIs supporting user profiles, saved trips, itinerary generation, event-level editing, summaries, and trip refinement.",
      "The interface includes calendar, timeline, map, weather, and AI editing views. I added Jest and Supertest coverage for key backend behavior, including itinerary generation and editing.",
    ],
    highlights: [
      "Built saved trips, itinerary generation, event editing, and trip refinement.",
      "Designed calendar, timeline, map, weather, and AI editing views.",
      "Added Jest and Supertest coverage around key backend behavior.",
    ],
    stack: [
      "React",
      "Vite",
      "Tailwind CSS",
      "Express",
      "Firebase Auth",
      "Firestore",
      "LLM APIs",
    ],
    date: 202506,
    location: "Mountain View, CA",
    links: [{ label: "Visit Wanderform", url: "https://wanderform.com" }],
  },
  {
    id: 6,
    title: "What Makes Games Popular?",
    type: "Research",
    brief:
      "CS229 machine learning project predicting Steam game popularity from metadata and engagement signals.",
    preview: "",
    imageList: [],
    description: [
      "For Stanford CS229, I studied whether static Steam metadata can predict and explain video game popularity. The project combined a Kaggle Steam dataset with Steam Web API and SteamSpy data, including ownership, playtime, reviews, and other engagement measures.",
      "We engineered a 513-dimensional feature space from genres, categories, platforms, languages, developers, publishers, pricing, achievements, descriptions, ownership, playtime, review sentiment, Metacritic scores, and discounts. We then trained regularized linear regression and PyTorch neural network models on a composite popularity score.",
      "We also used k-means and Gaussian Mixture Models to identify groups of similar games. The neural network modestly improved validation MSE over linear regression. K-means with k=7 produced the clearest stable clusters, while the Gaussian Mixture Models produced smaller and more overlapping groups.",
    ],
    highlights: [
      "Built a 513-dimensional feature set from Steam metadata and engagement signals.",
      "Compared regularized linear regression and PyTorch neural network models.",
      "Used k-means and Gaussian Mixture Models to identify interpretable game segments.",
    ],
    stack: ["Python", "PyTorch", "scikit-learn", "Steam API", "Clustering"],
    date: 202512,
    location: "Stanford University",
    links: [
      {
        label: "Read final report",
        document: "CS229ProjectFinalReport.pdf",
      },
    ],
  },
  {
    id: 7,
    title: "Beyond Full Fine-tuning",
    type: "Research",
    brief:
      "CS224N project comparing GPT-2 full fine-tuning with PEFT methods across NLP tasks.",
    preview: "",
    imageList: [],
    description: [
      "For Stanford CS224N, I helped study how GPT-2 performs on sentiment classification, paraphrase detection, and sonnet generation under full fine-tuning and parameter-efficient fine-tuning methods. We compared methods separately for each task instead of assuming that one method would perform best across all tasks.",
      "We implemented and compared bottleneck adapters, LoRA, IA3, prefix tuning, UniPELT-style hybrids, synthetic data augmentation, and Direct Preference Optimization. These methods were evaluated across classification, detection, and generation tasks with different data and structural demands.",
      "Full fine-tuning remained a reliable baseline, while PEFT methods reduced compute requirements and performed better on some tasks with limited data or strong structural constraints. The best validation results included 0.559 on SST-5, 0.984 on CFIMDB, 0.911 on paraphrase detection, and 42.62 chrF for sonnet generation.",
    ],
    highlights: [
      "Compared full fine-tuning with adapters, LoRA, IA3, prefix tuning, and UniPELT-style hybrids.",
      "Evaluated adaptation across sentiment classification, paraphrase detection, and sonnet generation.",
      "Found that PEFT methods performed well on some tasks with limited training data.",
    ],
    stack: ["Python", "PyTorch", "GPT-2", "LoRA", "Adapters", "DPO"],
    date: 202603,
    location: "Stanford University",
    links: [
      {
        label: "Read final report",
        document: "CS224NFinalReport.pdf",
      },
    ],
  },
];
